fix:  MockKubevirtClientInstance cause compile issue
notes:
../../gocode/pkg/mod/kubevirt.io/client-go@v0.58.0/kubecli/kubevirt_test_utils.go:32:9: cannot use MockKubevirtClientInstance (variable of type *MockKubevirtClient) as type KubevirtClient in return statement:
        *MockKubevirtClient does not implement KubevirtClient (missing NetworkingV1alpha1 method)